### ISSUE TITLE
Load in Python code broken since LINDI?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#153]
On a view like

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/f02db27e-82eb-41dd-865a-a08bb41491da/download/&dandisetId=000728&dandisetVersion=draft&tab=neurodata-item:/processing/ophys/DfOverF/DfOverF|RoiResponseSeries

If I press the 'Load in Python' to get a code snippet I get

```python
import h5py
import remfile

url = 'https://lindi.neurosift.org/dandi/dandisets/000728/assets/f02db27e-82eb-41dd-865a-a08bb41491da/zarr.json'

# open the remote file
f = h5py.File(remfile.File(url), 'r')

# load the neurodata object
X = f['/processing/ophys/DfOverF/DfOverF']

timestamps = X['timestamps']
data = X['data']

print(f'timestamps shape: {timestamps.shape}')
print(f'data shape: {data.shape}')
```

but trying to run that I get

```python
Traceback (most recent call last):
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-5f264a0e0372>", line 7, in <module>
    f = h5py.File(remfile.File(url), 'r')
                  ^^^^^^^^^^^^^^^^^
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/remfile/RemFile.py", line 67, in __init__
    self.length = int(response.headers["Content-Length"])
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-length'
```

Recommend some ability to test (in CI) if generated code can run without error

**Comment by magland** [comment]
Thanks @CodyCBakerPhD !
This should be fixed now. Would be great if you could quickly verify on your end.

Regarding CI... not in a position to implement that at this point.

**Comment by CodyCBakerPhD** [comment]
Now I get

```javasscript
Traceback (most recent call last):
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-d0070f03138d>", line 6, in <module>
    f = lindi.LindiH5pyFile.from_reference_file_system(url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/lindi/LindiH5pyFile/LindiH5pyFile.py", line 39, in from_reference_file_system
    return LindiH5pyFile.from_reference_file_system(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/lindi/LindiH5pyFile/LindiH5pyFile.py", line 47, in from_reference_file_system
    store = LindiReferenceFileSystemStore(rfs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codybaker/anaconda3/lib/python3.11/site-packages/lindi/LindiH5pyFile/LindiReferenceFileSystemStore.py", line 71, in __init__
    raise Exception(f"Problem with {k}: value must be a string or a list")
Exception: Problem with .zattrs: value must be a string or a list
```

**Comment by CodyCBakerPhD** [comment]
(when running)

```python
import lindi
url = 'https://lindi.neurosift.org/dandi/dandisets/000728/assets/f02db27e-82eb-41dd-865a-a08bb41491da/zarr.json'
# Load the remote file
f = lindi.LindiH5pyFile.from_reference_file_system(url)
# load the neurodata object
X = f['/processing/ophys/DfOverF/DfOverF']
timestamps = X['timestamps']
data = X['data']
print(f'timestamps shape: {timestamps.shape}')
print(f'data shape: {data.shape}')
```

(which is what neurosift gave me)

**Comment by magland** [comment]
Oops. Please upgrade lindi

```
pip install --upgrade lindi
```

to 0.2.1

LMK

**Comment by CodyCBakerPhD** [comment]
Works now!

**Comment by magland** [comment]
> Works now!

Great! Notice how fast it is with LINDI. :)
