### ISSUE TITLE
Error while running : neurosift view-nwb /path/to/file

### ISSUE THREAD

**Issue by navinfreeze** [flatironinstitute/neurosift#193]
Here is the error I am facing:

$ neurosift view-nwb /Users/navin/Documents/file.nwb

npm version: 10.7.0
node version: v20.15.1
/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/neurosift
/bin/sh: nvm: command not found
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nwb/bin/neurosift", line 8, in <module>
    sys.exit(neurosift())
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/nwb/lib/python3.10/site-packages/neurosift/cli.py", line 61, in view_nwb
    process = subprocess.Popen(['npm', 'run', 'start', tmpdir], cwd=f'{this_directory}/local-file-access-js', shell=shell, env=dict(os.environ, PORT=str(port)))
  File "/opt/anaconda3/envs/nwb/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/envs/nwb/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

I have npm installed anf the version is being printed by the cli.py file correctly. However, subprocess.Popen(['npm', 'run', 'start', tmpdir], cwd=f'{this_directory}/local-file-access-js', shell=shell, env=dict(os.environ, PORT=str(port))) does not run for same reason and says npm does not exist. Please help!

PS: I am using it on a MacOS

**Comment by magland** [comment]
@navinfreeze That's a strange error since `npm --version` seems to be working but for `npm run start` it is not finding the npm command. I made some tweaks to these function calls to help with the troubleshooting. Could you please try with version 0.2.9 from Python?

**Comment by magland** [comment]
@navinfreeze is this still a problem? Otherwise I will close the issue.
